version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./flaskblog:/flaskblog/flaskblog"
    tty: true
    #environment:
      #TZ: Asia/Tokyo
    command: python manage.py
  db:
    image: postgres:11
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: test01
      POSTGRES_PASSWORD: test01
      POSTGRES_DB: test01